export const GET_FAVORITE_SHOWS = 'GET_FAVORITE_SHOWS';
export const SELECT_SHOW = 'SELECT_SHOW';
export const GET_EPISODES = 'GET_EPISODES';

export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';
export const ERROR_LOG = 'ERROR_LOG';
