export const GET_SHOW = "GET_SHOW";
export const GET_FAVORITE_SHOWS = "GET_FAVORITE_SHOWS";

export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const ERROR_LOG = "ERROR_LOG";
